Resources:
                  
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: postgresassign 
      Engine: postgres 
      MultiAZ: True
      AllocatedStorage: '5'
      DBInstanceClass: db.t2.small 
      MasterUsername: DBUser
      MasterUserPassword: DBPassword
